- name: create users
  hosts: mca
  remote_user: ubuntu
  become: yes
  vars_files: user_passwords.yml
  tasks:
    - name: Create users
      user: name="{{item.key}}" password="{{item.value}}" shell="/bin/bash" update_password=on_create
      with_dict: "{{ user_passwords }}"
