- name: Install Packages
  hosts: networking
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: latest
    - name: "Update Repository cache"
      apt:
        update_cache: true
        force_apt_get: true

    - name: Install Docker
      apt:
        name: docker.io
        state: latest

